services:
  - type: web
    name: nexusmart-ecommerce
    runtime: node
    region: oregon
    plan: free
    branch: main
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.19.0
      - key: MONGODB_URI
        value: mongodb+srv://nexusmart-admin:cZfFthnSKtsCnlJB@nexusmart-cluster.46lpntt.mongodb.net/nexusmart?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: nexusmart_jwt_secret_key_production_2024_secure
      - key: JWT_REFRESH_SECRET
        value: nexusmart_refresh_token_secret_production_2024
      - key: JWT_EXPIRE
        value: 7d
      - key: JWT_REFRESH_EXPIRE
        value: 30d
      - key: CLIENT_URL
        value: https://nexusmart-d0c174bae61e.herokuapp.com
