services:
  - type: web
    name: nexusmart-ecommerce
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm install && cd client && npm install && npm run build && cd ..
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.19.0
